### PR TITLE
fix(api): replace .get("content") with .then() in renderBlock and renderInline

### LINKED ISSUE #516: `renderBlock` and `renderInline` broken since v6.1.8: `parser.parsePage(...).get is not a function`
## Summary

I'm developing a HonKit plugin that uses `this.renderBlock()` in a block processor.
Since v6.1.8, calling `this.renderBlock("markdown", body)` throws the following error at build time:

```
TypeError: parser.parsePage(...).get is not a function
```

- HonKit version: v6.1.8 and later (works fine on 6.1.7)

## Step to reproduce

1. Install a plugin that calls `this.renderBlock()` or `this.renderInline()` in a block's `process` function (e.g. [`honkit-plugin-admonition`](https://github.com/chick-p/honkit-plugin-admonition))
2. Add a block that triggers `renderBlock` to a Markdown page
3. Run `honkit build`

## Expected results

Build completes successfully and the block content is rendered as HTML.

## Actual results

```
TypeError: parser.parsePage(...).get is not a function
    at Object.renderBlock (node_modules/honkit/lib/api/encodeGlobal.js:103:50)
```

## Root cause

This appears to be a regression introduced by #508 (drop `q` in favour of a native Promise shim).

`renderBlock` and `renderInline` in `encodeGlobal.ts` call `.get("content")` on the value returned by `parsePage()` / `parseInline()`. With `q`, every promise had a built-in `.get(prop)` method that resolved the named property. The new `extendPromise` shim introduced in #508 does not add `.get()`, so calling `.get("content")` throws at runtime.

### PR DESCRIPTION
**Pull request by chick-p**
Fixes #516

### CODE REVIEW

**Review by azu — APPROVED** [review]
Thanks
